#!/bin/bash
#PBS -P RDS-FEI-NSEG-RW
#PBS -l select=1:ncpus=2:ngpus=1:mem=10gb
#PBS -l walltime=6:00:00

module load python/3.6.5
source /home/hngu4068/tensor_prob/bin/activate
module load cuda/10.0.130
module load openmpi-gcc/3.1.3

cd /project/RDS-FEI-NSEG-RW/mri_gan

python code/main.py --checkpoint-dir /project/RDS-FEI-NSEG-RW/tensorflow_checkpoints/mri_gan/initial --batch-size 24 --n-epochs 200
