#!/bin/bash
#PBS -P RDS-FEI-NSEG-RW
#PBS -l select=1:ncpus=1:ngpus=1:mem=4gb
#PBS -l walltime=10:00:00

module load python/2.7.9
#source ~/tf-nogpu/bin/activate
source ~/tensorflow/bin/activate
module load cuda/9.1.85 openmpi-gcc/3.0.0-cuda

#cd $PBS_O_WORKDIR
cd $HOME/mri_gan
python code/main3D.py --n_epoch 20 --data_dir /project/RDS-FEI-NSEG-RW/mri_cycle/mri --checkpoint_name 3d_initial --use_3D
